<?php

namespace Tests\Feature;

use App\Models\Category;
use Tests\TestCase;

class CategoryDbTest extends TestCase
{
    private $category;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $attr = [
            'name' => $this->faker->name,
            'description' => $this->faker->sentence
        ];

        $this->category = Category::create($attr);

    }

    /**
     * @test
     * @testdox Adding Category
     */
    public function testNewCategory()
    {
        self::assertDatabaseHas('categories', $this->category->getAttributes());
    }

    /**
     * @test
     * @testdox Updating Category
     */
    public function testUpdateCategory()
    {

        $this->category->description = null;
        $this->category->save();
        $this->assertNull($this->category->description);
        self::assertDatabaseHas('categories', $this->category->getAttributes());
    }

    /**
     * @test
     * @testdox Showing Category
     */
    public function testShowCategory()
    {

        self::assertDatabaseHas('categories', $this->category->getAttributes());
    }

    /**
     * @test
     * @testdox Removing Category
     */
    public function testDestroyCategory()
    {
        $this->category->delete();
        self::assertSoftDeleted('categories', $this->category->getAttributes());
    }
}
