<?php

namespace Tests\Feature;

use App\Models\Product;
use Tests\TestCase;

class ProductDbTest extends TestCase
{
    private $product;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $attr = [
            'name' => $this->faker->name,
            'description' => $this->faker->sentence
        ];

        $this->product = Product::create($attr);

    }

    /**
     * @test
     * @testdox Adding Product
     */
    public function testNewProduct()
    {
        self::assertDatabaseHas('products', $this->product->getAttributes());
    }

    /**
     * @test
     * @testdox Updating Product
     */
    public function testUpdateProduct()
    {

        $this->product->description = null;
        $this->product->save();
        $this->assertNull($this->product->description);
        self::assertDatabaseHas('products', $this->product->getAttributes());
    }

    /**
     * @test
     * @testdox Showing Product
     */
    public function testShowProduct()
    {

        self::assertDatabaseHas('products', $this->product->getAttributes());
    }

    /**
     * @test
     * @testdox Removing Product
     */
    public function testDestroyProduct()
    {
        $this->product->delete();
        self::assertSoftDeleted('products', $this->product->getAttributes());
    }
}
